version: 2

sources:
  - name: core
    database: "{{ var('raw_database', target.database) }}"
    schema: "{{ var('raw_schema', 'PUBLIC') }}"
    tables:
      - name: Client
      - name: Project
      - name: Deliverable
      - name: ProjectExpense
      - name: ClientFeedbackInitial
