version: 2

sources:
  - name: core
    database: "{{ var('raw_database', 'SQLITE_INGEST_DB_1772077572') }}"
    schema: "{{ var('raw_schema', 'PUBLIC') }}"
    tables:
      - name: BusinessUnit
      - name: Client
      - name: ClientFeedbackInitial
      - name: Consultant
      - name: ConsultantDeliverable
      - name: ConsultantTitleHistory
      - name: Deliverable
      - name: IndirectCosts
      - name: Location
      - name: NonBillable
      - name: Payroll
      - name: Project
      - name: ProjectBillingRate
      - name: ProjectExpense
      - name: ProjectTeam
      - name: Title
